If you receive `resetPassword`, authentication flow could not proceed without resetting the password. The next step is to invoke `resetPassword` api and follow the reset password flow.

<BlockSwitcher>

<Block name="Async/Await">

```swift
func resetPassword(username: String) async {
    do {
        let resetPasswordResult = try await Amplify.Auth.resetPassword(for: username)
        print("Reset password succeeded.")
        print("Next step: \(resetPasswordResult.nextStep)")
    } catch let error as AuthError {
        print("Reset password  failed \(error)")
    } catch {
        print("Unexpected error: \(error)")
    }
}
```

</Block>

<Block name="Combine">

```swift
func resetPassword(username: String) -> AnyCancellable {
    Amplify.Publisher.create {
        try await Amplify.Auth.resetPassword(for: username)
        }.sink {
            if case let .failure(authError) = $0 {
                print("Reset password  failed \(authError)")
            }
        }
        receiveValue: { resetPasswordResult in
            print("Reset password succeeded.")
            print("Next step: \(resetPasswordResult.nextStep)")
        }
}
```

</Block>

</BlockSwitcher>