<BlockSwitcher>

<Block name="Async/Await">

```swift
func signIn(username: String, password: String) async {
    do {
        let signInResult = try await Amplify.Auth.signIn(
            username: username, 
            password: password
            )
        if signInResult.isSignedIn {
            print("Sign in succeeded")
        }
    } catch let error as AuthError {
        print("Sign in failed \(error)")
    } catch {
        print("Unexpected error: \(error)")
    }
}
```

</Block>

<Block name="Combine">

```swift
func signIn(username: String, password: String) -> AnyCancellable {
    Amplify.Publisher.create {
        try await try await Amplify.Auth.signIn(
            username: username, 
            password: password
            )
    }.sink {
        if case let .failure(authError) = $0 {
            print("Sign in failed \(authError)")
        }
    }
    receiveValue: { signInResult in
        if signInResult.isSignedIn {
            print("Sign in succeeded")
        }
    }
}
```

</Block>

</BlockSwitcher>

You will know the sign in flow is complete if you see the following in your console window:

```console
Sign in succeeded
```
