```swift
do {
    try await Amplify.DataStore.start()
    print("DataStore started")
} catch let error as DataStoreError {
    print("Error starting DataStore: \(error)")
} catch {
    print("Unexpected error \(error)")
}

```
